landscapeMemberClasses:
   - name: Premier Membership
     category: Premier
   - name: General Membership
     category: General
   - name: Associate Membership
     category: Associate
slug: lfedge
landscapeMemberCategory: LF Edge Member Company
memberSuffix: " (member)"
