landscapeName: LFEdge
landscapeMemberClasses:
   - name: Premier Membership
     category: Premier
   - name: General Membership
     category: General
   - name: Associate Membership
     category: Associate
project: a092M00001EzWy7QAF # LF Edge Foundation
landscapeMemberCategory: LF Edge Member Company
memberSuffix: " (member)"
